CREATE TABLE answers
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_answers PRIMARY KEY (id)
);

CREATE TABLE choices
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    answer      VARCHAR(255)                            NOT NULL,
    question_id BIGINT,
    CONSTRAINT pk_choices PRIMARY KEY (id)
);

CREATE TABLE person
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_person PRIMARY KEY (id)
);

CREATE TABLE "poll-results"
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    poll_id   BIGINT,
    person_id BIGINT,
    CONSTRAINT "pk_poll-results" PRIMARY KEY (id)
);

CREATE TABLE polls
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    start_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_polls PRIMARY KEY (id)
);

CREATE TABLE questions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question_type INTEGER                                 NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    poll_id       BIGINT,
    CONSTRAINT pk_questions PRIMARY KEY (id)
);

CREATE TABLE results_choices
(
    choices_id BIGINT NOT NULL,
    result_id  BIGINT NOT NULL
);

ALTER TABLE choices
    ADD CONSTRAINT FK_CHOICES_ON_QUESTION FOREIGN KEY (question_id) REFERENCES questions (id);

ALTER TABLE "poll-results"
    ADD CONSTRAINT "FK_POLL-RESULTS_ON_PERSON" FOREIGN KEY (person_id) REFERENCES person (id);

ALTER TABLE "poll-results"
    ADD CONSTRAINT "FK_POLL-RESULTS_ON_POLL" FOREIGN KEY (poll_id) REFERENCES polls (id);

ALTER TABLE questions
    ADD CONSTRAINT FK_QUESTIONS_ON_POLL FOREIGN KEY (poll_id) REFERENCES polls (id);

ALTER TABLE results_choices
    ADD CONSTRAINT fk_rescho_on_choice FOREIGN KEY (choices_id) REFERENCES choices (id);

ALTER TABLE results_choices
    ADD CONSTRAINT fk_rescho_on_poll_result FOREIGN KEY (result_id) REFERENCES "poll-results" (id);